# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.add("Deldir"); Pkg.build("VoronoiCorners"); Pkg.test("VoronoiCorners"; coverage=true)'
