# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
# Deldir needed for testing; Deldir needs Fortran
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
after_success:
   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
